name: CI

on:
  push:
    branches: ["**"] # run on any branch
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - "README.md"
      - "TESTING.md"
      - "CONTRIBUTING.md"

  pull_request:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - "README.md"
      - "TESTING.md"
      - "CONTRIBUTING.md"

# cancel older runs of the same branch/PR if a new commit arrives
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22] # test against supported LTS lines

    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci
        # If you don't commit package-lock.json, swap to:
        # run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Test (coverage)
        run: npm run test:coverage

      - name: Build
        run: npm run build

      - name: Sanity pack (dry-run)
        run: npm pack --dry-run

      - name: Upload coverage (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-node-${{ matrix.node }}
          path: coverage
  docs-and-housekeeping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 18 }
      - run: npm ci
      - run: npm run verify:docs
    continue-on-error: true
